// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onServoSpeedLChange();
void onServoSpeedRChange();
void onRobotStateChange();

float servo_speed_l;
float servo_speed_r;
int robot_state;

void initProperties(){

  ArduinoCloud.addProperty(servo_speed_l, READWRITE, ON_CHANGE, onServoSpeedLChange);
  ArduinoCloud.addProperty(servo_speed_r, READWRITE, ON_CHANGE, onServoSpeedRChange);
  ArduinoCloud.addProperty(robot_state, READWRITE, ON_CHANGE, onRobotStateChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
